apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../workflows
patches:
- path: ingress_patch.json
  target:
    group: networking.k8s.io
    kind: Ingress
    name: argo-server
    version: v1
images:
- name: quay.io/argoproj/argocli
  newName: quay.io/argoproj/argocli
  newTag: v2.12.4
