apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../../argo-workflows/manifests/base
- ../../../argo-workflows/manifests/cluster-install/workflow-controller-rbac
- ../../../argo-workflows/manifests/cluster-install/argo-server-rbac
- ingress.yaml
patchesStrategicMerge:
- config.yaml
namespace: argo
